apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor

metadata:
  name: {{ .Release.Name }}-backend

  labels:
    release: monitoring

spec:
  selector:
    matchLabels:
      app: {{ .Release.Name }}-backend

  endpoints:
    - port: http
      path: /metrics
      interval: 15s